# Generated by Django 4.2.13 on 2024-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flatnumb',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
