# Generated by Django 4.2.13 on 2024-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='flatnumb',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
