name: "sandbox"

services:
  traefik:
    image: traefik:2.9
    hostname: traefik # http://localhost:8088
    ports:
      - "8080:80"
#      - "8088:8080" # dashboard
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - keycloak # http://keycloak.local.gd:8080/
      - mailhog  # http://mailhog.local.gd:8080

  postgres:
    image: postgres:15-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata

  keycloak:
    image: keycloak/keycloak:20.0
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    hostname: keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.local.gd`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: start-dev --db postgres --db-url-host keycloak-db --db-username keycloak --db-password keycloak --import-realm
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15-alpine
    hostname: keycloak-db
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak

  mailhog:
    image: mailhog/mailhog:v1.0.1
    hostname: mailhog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.local.gd`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    ports:
      - "25:1025"

volumes:
  postgres:
  keycloak-db:
