services:
  keycloak:
    image: keycloak/keycloak:20.0
    container_name: keycloak
    restart: unless-stopped
    hostname: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - PROXY_ADDRESS_FORWARDING=true
    command: start-dev --proxy passthrough --db postgres --db-url-host keycloak-db --db-username keycloak --db-password keycloak
    depends_on:
      - keycloak-db
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    restart: unless-stopped
    hostname: keycloak-db
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak

volumes:
  keycloak-db:
